### ISSUE TITLE
Whitelist feature broken, allows organizer registration from any domain

### ISSUE THREAD

**Issue by alex-418** [BCcampus/validate-by-domain#22]
The domains in the whitelist are supposed to stop the registration of organizer accounts without a valid domain. Dev branch currently allows registration with any domain, and ignores the whitelist.

**Comment by bdolor** [comment]
resolved via https://github.com/BCcampus/validate-by-domain/commit/c5ed8b28c2e73de9c9f7f9ee809f794c5f6974bc
