### ISSUE TITLE
Pressbooks Integration

### ISSUE THREAD

**Issue by johnpeterm** [BCcampus/validate-by-domain#23]
### Description 

Is this plugin work with Pressbooks.

**Expected behaviour** 

[What you expect/want to happen]

**Actual behaviour** 

[What actually happened]

### Steps to reproduce the problem

[First Step, Second Step, etc]

### System Information

- Validate by Domain: [Enter Version here] 
- WordPress: [Enter WP Version number here]

**Comment by bdolor** [comment]
It is a plugin that works with BuddyPress - largely to support two internal projects, but looking to shape it for wider use. Definitely not compatible with PB.
